#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     colorR,         sensorCOLORFULL)
#pragma config(Sensor, S3,     colorL,         sensorCOLORFULL)
#pragma config(Sensor, S4,     irSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorB,          grabL,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          grabR,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    liftLow,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    liftHigh,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  motorB,          motorL,     tmotorNXT, openLoop, encoder)
//#pragma config(Motor,  motorC,          motorR,    tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
TFileHandle hFileHandle;
TFileIOResult nIoResult;
char sOutput[100];

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "7391RobotDriver.c" //Include file of Robot Drivers.
#include "7391AutoUtils.c" //Include file of Autonomous Utilities

#define RAMP 1
int loc = RAMP;
//int loc = ZONE;
int color = BLUECOLOR;
//int color = BLUECOLOR;
//const int DELAY = 10; //seconds
const int DELAY = 0;

#define IR_LEFT 2
#define IR_RIGHT 8

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	char * sFileName = "debug.txt";
	short nFileSize =10000;






	eraseDisplay();
	nxtDisplayTextLine(0, "Autonomous Period");

	Delete(sFileName,nIoResult);
	OpenWrite(hFileHandle, nIoResult, sFileName, nFileSize);
	WriteText(hFileHandle, nIoResult, "Autonomous Period\n");

	nPidUpdateInterval = 20;

	nMotorEncoder[motorR] = 0;
	nMotorEncoder[motorL] = 0;

	servoChangeRate[liftHigh] = 1;
	servoChangeRate[liftLow] = 1;

	liftBottom();

	wait1Msec(10);

	return;
}
//////////////////////////////////////////////////////////////////////////////////////////////
//Autonomous Period

//-by Arjun Verma (FTC Team Error 7391)



//(POSITION 1 - perpendicular)

//(POSITION 2 - 45 degrees left of POS 2)

//(POSITION 3 - 45 degrees right of POS 1)

//RAMP MODE

//Get off ramp
//Find optimal position to detect IR beacon
	//if IR beacon is detected at position one then do:
		//go forward till IR beacon is perpendicular to robot
		//go to the rolling goals and score in the highest goal
		//pick up rolling goal
		//turn toward IR beacon
		//score one ball in the center goal
		//place rolling goal in the parking zone
		//get other rolling goals if time
////////////////////////////////////////////////////////////////////////////////////////////////////


task main()
{
	initializeRobot();

	//waitForStart(); // Wait for the beginning of autonomous phase.


	//_______________________________________________________________________________________________________________________
	time100[1] = 0;

	liftBasket();

	wait10Msec(DELAY*100); //wait for other side
	eraseDisplay();
	int beacon;
	//nxtDisplayTextLine(1, "here 21" );
	//while (nNxtButtonPressed != kLeftButton){}
	if (RAMP == loc)
		beacon = getBeaconVal(12);

	else //if (ZONE == loc)
		beacon = getBeaconVal(IR_RIGHT);

	//nxtDisplayTextLine(1, "here 22" );
	while (nNxtButtonPressed != kEnterButton){}
	goDownRamp();

	//dropNramp(side, distance, color);

	Close(hFileHandle, nIoResult);
}
