#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorR,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorL,        tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    move1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    move2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
//#include "7391RobotDriver.c"  //Include file to "handle" the Bluetooth messages.


///////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void moveInches(float distance, int speed);
void pivotDegrees(float degrees, int speed, bool dir);
void turnDegrees(int degrees);

#define DRIVE_DIAMETER 3
#define FORWARD 0
#define BACKWARD 1



task main()
{
  //initializeRobot();

  //waitForStart(); // Wait for the beginning of autonomous phase.
  servo[move1] = 128;
  servo[move2] = 128;

  wait10Msec(100);
 	moveInches(60,20);

 	servo[move1] = 144;
  servo[move2] = 144;

  wait10Msec(100);
 	moveInches(24,20);


}

void turnDegrees(int degrees){
	//16degrees = 90 degrees
  //positive is right
	//negative is left
	int ticks = 128+(16/90)*degrees;
	servo[move1] = ticks;
	servo[move2] = ticks;

}

void pivotDegrees(float degrees, int speed, bool dir )
{
	int lastEncoderL = -1;
	int currEncoderL = 0;
	int ticks = 3200*degrees/90;

	nMotorEncoder[motorR] = 0;
	nMotorEncoder[motorL] = 0;


	if(degrees > 0 && dir == FORWARD){
		nMotorEncoderTarget[motorR] = ticks;
		motor[motorR] = speed;
		motor[motorL] = 0;
		while(nMotorRunState[motorR] != runStateIdle)
		{
			//currEncoderL =	nMotorEncoder[motorL];
			//if (lastEncoderL < currEncoderL + 10){
			//	break;
			//}
			//lastEncoderL = currEncoderL;
		}

	}//endif
	else if(degrees < 0 && dir == BACKWARD){
		nMotorEncoderTarget[motorR] = -ticks;
		motor[motorR] = -speed;
		motor[motorL] = 0;
		while(nMotorRunState[motorR] != runStateIdle)
		{
			//currEncoderL =	nMotorEncoder[motorL];
			//if (lastEncoderL < currEncoderL + 10){
			//	break;
			//}
			//lastEncoderL = currEncoderL;
		}
	}//endif
}

void moveInches(float distance, int speed)
{
	int lastEncoderL = -1;
	int currEncoderL = 0;
	int ticks = 1440/(DRIVE_DIAMETER*PI)*distance;
	nMotorEncoder[motorR] = 0;
	nMotorEncoder[motorL] = 0;
	nMotorEncoderTarget[motorR] = ticks/2;
	nMotorEncoderTarget[motorL] = ticks/2;

	if(distance > 0){
		motor[motorR] = speed;
		motor[motorL] = speed;
	}
	else{
		motor[motorR] = -speed;
		motor[motorL] = -speed;
	}

	while(nMotorRunState[motorR] != runStateIdle)
	{
		//currEncoderL =	nMotorEncoder[motorL];
		//if (lastEncoderL < currEncoderL + 10){
		//	break;
		//}
		//lastEncoderL = currEncoderL;
	}
	motor[motorR] = 0;
	motor[motorL] = 0;
}
