#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     colorR,         sensorNone)
#pragma config(Sensor, S3,     colorL,         sensorNone)
#pragma config(Sensor, S4,     irSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          grabL,         tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          grabR,         tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    move1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    move2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    shoulder,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    elbow,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    collector,            tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//
////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
//#include "hitechnic-gyro.h"
//#include "7391RobotDriver.c"


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
//void  setWheelDegrees(int value);
#define A_BUTT 2
#define Y_BUTT 4

task main()
{
	const int IS_PRESSED = 1;
	int heading = 0;
	const int HEADING_OFFSET = 144;
	const float MAX_MOTOR_SPEED=60;
	const float SLOW_MOTOR_SPEED=30;
	const int THRESH_VAL = 6;
	const float RADIANS_TO_SERVO = 32/PI;
	//	initializeRobot();
	//waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		getJoystickSettings(joystick);

		if(joystick.joy1_TopHat == -1){
			if(abs(joystick.joy1_y1)>THRESH_VAL||abs(joystick.joy1_x1)>THRESH_VAL){
				heading = -(atan2(joystick.joy1_y1,joystick.joy1_x1))*RADIANS_TO_SERVO;

				servo[move1] = heading+HEADING_OFFSET;
				servo[move2] = heading+HEADING_OFFSET;
			}

			if(joy1Btn(Y_BUTT) == IS_PRESSED){
				motor[motorL] = MAX_MOTOR_SPEED;
				motor[motorR] = MAX_MOTOR_SPEED;
			}
			else if(joy1Btn(A_BUTT) == IS_PRESSED){
				motor[motorL] = SLOW_MOTOR_SPEED;
				motor[motorR] = SLOW_MOTOR_SPEED;
			}
			else {
				motor[motorL] = 0;
				motor[motorR] = 0;
			}

		}
		else {
			servo[move1]=136;
			servo[move2]=120;

			if(joystick.joy1_TopHat == 7 || joystick.joy1_TopHat == 6 || joystick.joy1_TopHat == 5){
				motor[motorL] = 20;
				motor[motorR] = -20;
			}
			else if(joystick.joy1_TopHat == 1 || joystick.joy1_TopHat == 2 || joystick.joy1_TopHat == 3){
				motor[motorL] = -20;
				motor[motorR] = 20;
			}
			else{
				motor[motorL] = 0;
				motor[motorR] = 0;
			}
		}

		if(joy2Btn(Y_BUTT) == IS_PRESSED){
			servo[elbow] = 255;
			wait1Msec(500);
			servo[wrist]  =255;
			wait1Msec(500);
			servo[shoulder]  = 0;
			wait1Msec(600);
			servo[elbow] = 0;
			servo[wrist] = 0;
		}

		// Insert code to have servos and motors respond to joystick and button values.

		// Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
		// You may be able to find "snippets" of code that are similar to the functions that you want to
		// perform.
	}
}

//void  setWheelDegrees(int value){
//	servo[wheel1] = value;
//	servo[wheel2] = value;
//	servo[wheel3] = value;
//	servo[wheel4] = value;
//}
