#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          motorD,        tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          motorE,        tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    wheel1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    wheel2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//
 ///////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
//#include "hitechnic-gyro.h"


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
//void  setWheelDegrees(int value);

task main()
{
	const int threshVal = 6;
	initializeRobot();
	//waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		if(joystick.joy1_y1>threshVal){
			//SensorType[gyro] = gyro.
			//HTGYROstartCal(HTGYRO);
			//HTGYROsetCal(HTGYRO, 0);
			servo[wheel1] = 128;
			servo[wheel2] = 128;

			motor[motorD] = joystick.joy1_y1;
			motor[motorE] = joystick.joy1_y1;
			//setWheelDegrees(joystick.joy1_y1);
		}
		else if(joystick.joy1_y1<-threshVal){
			//SensorType[gyro] = gyro.
			//HTGYROstartCal(HTGYRO);
			//HTGYROsetCal(HTGYRO, 0);
			//servo[wheel1] = joystick.joy1_y1;
			//servo[wheel2] = joystick.joy1_y1;
			motor[motorD] = joystick.joy1_y1;
			motor[motorE] = joystick.joy1_y1;
		//	setWheelDegrees(-(joystick.joy1_y1));
		}
		// Insert code to have servos and motors respond to joystick and button values.

		// Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
		// You may be able to find "snippets" of code that are similar to the functions that you want to
		// perform.
	}
}

//void  setWheelDegrees(int value){
//	servo[wheel1] = value;
//	servo[wheel2] = value;
//	servo[wheel3] = value;
//	servo[wheel4] = value;
//}
