#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  motorA,          raiseA,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          grabL,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          grabR,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    liftLow,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    liftHigh,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
//#pragma config(Sensor, S2,     touch,          sensorTouch)
//#pragma config(Sensor, S3,     light,          sensorLightActive)
///////////////////////////////////////////////////////////////////////////////////////////////////
//#pragma config(Sensor, S4,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver1.c"  //Include file to "handle" the Bluetooth messages.
#include "7391RobotDriver.c"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//																																																	//
//                                    initializeRobot																								//
//																																																	//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot		//
// and the variables within your program.																														//
//																																																	//
// In most cases, you may not have to add any code to this function and it will remain "empty".			//
//																																																	//
//////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	servoChangeRate[liftHigh] = 1;				//10 pos every 10 msec			Default is 20 msec
	servoChangeRate[liftLow] = 1;				//10 pos every 10 msec			Default is 20 msec
	nPidUpdateInterval = 20;
	liftBottom();

	//servo[liftHigh] = 175;
	//servo[liftLow] = 92;

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
////////////////////////////////////////////////////////////////////////////////////////////////////

const float LOW_MOTOR_THRESH = 10;
//const float SLOW = 50/127;
//const float TURBO = 100/127;

void joystick2Move(int powerThresh);

task main()
{

	bool raiseFlag = false;
	bool lowerFlag = false;
	bool hangFlag = false;

	int servoHighTarget;
	int servoLowTarget;

	const int IS_PRESSED = 1;
	const int IS_NOT_PRESSED = 0;
	const int HIGH_OF_HIGH = 35;
	const int HIGH_OF_LOW = 240;
	const int LOW_OF_LOW = 87;
	const int LOW_OF_HIGH = 158;


#define X_BUTT 1
#define B_BUTT 3
#define A_BUTT 2
#define Y_BUTT 4
#define TURBO_BUTT 6

	waitForStart();   // wait for start of tele-op phase.

	initializeRobot();

	bSystemLeaveServosEnabledOnProgramStop = true;

	while (1 == 1){
		getJoystickSettings(joystick);
		nxtDisplayTextLine(2,"highServo=%d",ServoValue[liftHigh] );
		nxtDisplayTextLine(1,"y1=%d",joystick.joy1_y1 );
		nxtDisplayTextLine(3,"lowServo=%d",ServoValue[liftLow]);
		nxtDisplayTextLine(4,"y2=%d",joystick.joy1_y2 );



		//X Button pressed sucks in the blocks.
		if(joy2Btn(X_BUTT) == IS_PRESSED){
			motor[motorB] = 100;
			motor[motorC] = 100;
		}

		//A Button pressed spits out the blocks.
		else if(joy2Btn(A_BUTT) == IS_PRESSED){
			motor[motorB] = -100;
			motor[motorC] = -100;
		}

		//None Pressed turns off the grabbing motors.
		else if(joy2Btn(A_BUTT) == IS_NOT_PRESSED && joy2Btn(X_BUTT) == IS_NOT_PRESSED && joy2Btn(Y_BUTT) == IS_NOT_PRESSED){
			motor[motorB] = 0;
			motor[motorC] = 0;
			motor[motorA] = 0;
		}
		if (joy2Btn(Y_BUTT) == IS_PRESSED){
			motor[motorA] = 100;
		}


		if(joy1Btn(TURBO_BUTT) == IS_PRESSED){
			joystick2Move(100);
		}
		else{
			joystick2Move(60);
		}

		//if (joy2Btn(6) == IS_PRESSED){
		//	servo[liftHigh] = LOW_OF_HIGH;
		//}
		//else if (joy2Btn(5) == IS_PRESSED){
		//	servo[liftHigh] = HIGH_OF_HIGH;
		//}

		if (joy2Btn(6) == IS_PRESSED){
			//if(raiseFlag == false){
			liftBasket();
			raiseFlag = true;
			//	servoHighTarget--;
			//	servoLowTarget++;
			//	if(servoHighTarget<HIGH_OF_HIGH){
			//		servoHighTarget = HIGH_OF_HIGH;
			//	}
			//	if(servoLowTarget>HIGH_OF_LOW){
			//		servoLowTarget = HIGH_OF_LOW;
			//	}
			//	servo[liftHigh] = servoHighTarget;
			//	servo[liftLow] = servoLowTarget;
			//	wait10Msec(2);
			//}
			//}
		}
		else{
			raiseFlag = false;
		}


		if(joy2Btn(5) == IS_PRESSED){
			//if(lowerFlag == false){
			liftBottom();
			lowerFlag = true;
			//servoHighTarget++;
			//servoLowTarget--;
			//if(servoHighTarget>LOW_OF_HIGH){
			//	servoHighTarget = LOW_OF_HIGH;
			//}
			//if(servoLowTarget<LOW_OF_LOW){
			//	servoLowTarget = LOW_OF_LOW;
			//}
			//servo[liftHigh] = servoHighTarget;
			//servo[liftLow] = servoLowTarget;
			//wait10Msec(2);
		}
		else{
			lowerFlag = false;
		}
		if(joy2Btn(8) == IS_PRESSED){
			if(hangFlag == false){
			liftHang();
			hangFlag = true;
			//servoHighTarget++;
			//servoLowTarget--;
			//if(servoHighTarget>LOW_OF_HIGH){
			//	servoHighTarget = LOW_OF_HIGH;
			//}
			//if(servoLowTarget<LOW_OF_LOW){

			//	servoLowTarget = LOW_OF_LOW;
			//}
			//servo[liftHigh] = servoHighTarget;
			//servo[liftLow] = servoLowTarget;
			//wait10Msec(2);
			}
		}
		else{
				hangFlag = false;
		}
	}
}



//Insert code to have servos and motors respond to joystick and button values.

//Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
//You may be able to find "snippets" of code that are similar to the functions that you want to
//perform.


void joystick2Move(int powerThresh){
	if(abs(joystick.joy1_y1)<LOW_MOTOR_THRESH && abs(joystick.joy1_x2)<LOW_MOTOR_THRESH){
		motor[motorL] = 0;
		motor[motorR] = 0;
	}
	else if(joystick.joy1_y1>LOW_MOTOR_THRESH){
		motor[motorL] = (joystick.joy1_y1*powerThresh)/127;
		motor[motorR] = (joystick.joy1_y1*powerThresh)/127;
		if(abs(joystick.joy1_x2) < LOW_MOTOR_THRESH){
			motor[motorR] = (joystick.joy1_y1*powerThresh)/127;
			motor[motorL] = (joystick.joy1_y1*powerThresh)/127;
		}
		else if(joystick.joy1_x2 > LOW_MOTOR_THRESH){
			motor[motorR] = ((joystick.joy1_y1-joystick.joy1_x2)*powerThresh)/127;
			motor[motorL] = (joystick.joy1_y1*powerThresh)/127;
		}
		else if(joystick.joy1_x2 < LOW_MOTOR_THRESH){
			motor[motorL] = ((joystick.joy1_y1+joystick.joy1_x2)*powerThresh)/127;
			motor[motorR] = (joystick.joy1_y1*powerThresh)/127;
		}
	}

	else if(joystick.joy1_y1< -LOW_MOTOR_THRESH){
		motor[motorL] = (joystick.joy1_y1*powerThresh)/127;
		motor[motorR] = (joystick.joy1_y1*powerThresh)/127;
		if(abs(joystick.joy1_x2) < LOW_MOTOR_THRESH){
			motor[motorR] = (joystick.joy1_y1*powerThresh)/127;
			motor[motorL] = (joystick.joy1_y1*powerThresh)/127;
		}
		else if(joystick.joy1_x2 > LOW_MOTOR_THRESH){
			motor[motorR] = ((joystick.joy1_y1+joystick.joy1_x2)*powerThresh)/127;
			motor[motorL] = (joystick.joy1_y1*powerThresh)/127;
		}
		else if(joystick.joy1_x2 < LOW_MOTOR_THRESH){
			motor[motorL] = ((joystick.joy1_y1-joystick.joy1_x2)*powerThresh)/127;
			motor[motorR] = (joystick.joy1_y1*powerThresh)/127;
		}
	}
	else if(joystick.joy1_x2>LOW_MOTOR_THRESH){
		motor[motorL] = (joystick.joy1_x2*powerThresh)/127;
		motor[motorR] = -(joystick.joy1_x2*powerThresh)/127;
	}
	else if(joystick.joy1_x2<-LOW_MOTOR_THRESH){
		motor[motorR]  = -(joystick.joy1_x2*powerThresh)/127;
		motor[motorL] = (joystick.joy1_x2*powerThresh)/127;
	}
}
