#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
//#pragma config(Motor,  mtr_S1_C1_1,     ,              tmotorNone, openLoop)
//#pragma config(Motor,  mtr_S1_C1_2,     ,              tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//





/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to initialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
//
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#define LEFT_BUTTON			2
#define RIGHT_BUTTON		1
#define ORANGE_BUTTON		3


task main()
{
	int powerL = 0;
	int powerR = 0;
	bool bOrange = true;


	initializeRobot();

	//waitForStart();   // wait for start of tele-op phase

	while (1 == 1){
		for(int i=0; i<10000; i++){
		}
		//wait10Msec(100);
		nxtDisplayTextLine(1,"button=%d",nNxtButtonPressed );
		nxtDisplayTextLine(6,"powerL=%d powerR=%d",powerL, powerR );


		if(nNxtButtonPressed == ORANGE_BUTTON){
			if(bOrange == true){
				bOrange = false;
				motor[motorL] = powerL;
				motor[motorR] = powerR;
			}
			else {
				bOrange = false;
				motor[motorL] = 0;
				motor[motorR] = 0;
			}
		}
		else if(nNxtButtonPressed == RIGHT_BUTTON){
			powerL = powerL+1;
			powerR = powerR+1;
			motor[motorL] = powerL;
			motor[motorR] = powerR;

		}
		else if(nNxtButtonPressed == LEFT_BUTTON){
			powerL = powerL-1;
			powerR = powerR-1;
			motor[motorL] = powerL;
			motor[motorR] = powerR;
		}
	}

}








// Insert code to have servos and motors respond to joystick and button values.

// Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
// You may be able to find "snippets" of code that are similar to the functions that you want to
// perform.
