#pragma config(Sensor, S3,     kGyroSensor,    sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "GyroDriver.c"
//#define kGyroSensor = 1;
const tSensors GyroSensor = (tSensors) S1;   //gyro sensor//

#define offset 598       //offset value may vary depending on sensor & temperature
long Gyro_value;



task main()
{
   Gyro_value=SensorValue(GyroSensor)-offset;  //read the gyro sensor
	StopTask(GyroDeviceDriver);
	nxtDisplayBigTextLine(3, "gyro=%d", Gyro_value);
}
