#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          raiseA,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          grabL,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          grabR,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    lift,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
//#pragma config(Motor,  mtr_S1_C1_1,     ,              tmotorNone, openLoop)
//#pragma config(Motor,  mtr_S1_C1_2,     ,              tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	nPidUpdateInterval = 20;
	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
////////////////////////////////////////////////////////////////////////////////////////////////////

const float LOW_MOTOR_THRESH = 7;
const float SLOW = 50/127;
const float TURBO = 100/127;

void joystick2MoveSlowly();
void joystick2MoveTurbo();


task main()
{
	const int IS_PRESSED = 1;
	const int IS_NOT_PRESSED = 0;

#define X_BUTT 1
#define B_BUTT 3
#define A_BUTT 2
#define Y_BUTT 4
#define TURBO_BUTT 8


	//waitForStart();   // wait for start of tele-op phase

	while (1 == 1){
		initializeRobot();

		getJoystickSettings(joystick);
		nxtDisplayTextLine(1,"x1=%d",joystick.joy1_x1 );
		nxtDisplayTextLine(2,"y1=%d",joystick.joy1_y1 );
		nxtDisplayTextLine(3,"x2=%d",joystick.joy1_x2 );
		nxtDisplayTextLine(4,"y2=%d",joystick.joy1_y2 );




		if(joy1Btn(TURBO_BUTT) == IS_PRESSED){
			joystick2MoveTurbo();
		}
		else{
			joystick2MoveSlowly();
		}

		servo[lift] = joystick.joy2_y1;

		//X Button pressed sucks in the blocks.
		if(joy2Btn(X_BUTT) == IS_PRESSED){
			motor[grabR] = 100;
			motor[grabL] = 100;
		}

		//A Button pressed spits out the blocks.
		else if(joy2Btn(A_BUTT) == IS_PRESSED){
			motor[grabR] = -100;
			motor[grabL] = -100;
		}

		//None Pressed turns off the grabbing motors.
		else if(joy2Btn(B_BUTT) == IS_NOT_PRESSED && joy2Btn(X_BUTT) == IS_NOT_PRESSED && joy2Btn(Y_BUTT) == IS_NOT_PRESSED){
			motor[grabR] = 0;
			motor[grabL] = 0;
			motor[raiseA] = 0;
		}
		else if (joy2Btn(Y_BUTT) == IS_PRESSED){
			motor[raiseA] = 100;
		}
	 	// Insert code to have servos and motors respond to joystick and button values.

		// Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
		// You may be able to find "snippets" of code that are similar to the functions that you want to
		// perform.
	}
}

void joystick2MoveSlowly(){
	if(abs(joystick.joy1_y1)<LOW_MOTOR_THRESH){
		motor[motorL] = 0;
	}
	else {
		motor[motorL] = (joystick.joy1_y1*50)/127;
	}

	if(abs(joystick.joy1_y2)<LOW_MOTOR_THRESH){
		motor[motorR] = 0;
	}
	else {
		motor[motorR] = (joystick.joy1_y2*50)/127;
	}
}

void joystick2MoveTurbo(){

	if(abs(joystick.joy1_y1)<LOW_MOTOR_THRESH){
		motor[motorL] = 0;
	}
	else {
		motor[motorL] = (joystick.joy1_y1*100)/127;
	}

	if(abs(joystick.joy1_y2)<LOW_MOTOR_THRESH){
		motor[motorR] = 0;
	}
	else {
		motor[motorR] = (joystick.joy1_y2*100)/127;
	}
}
