#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                           - Line Tracker -                                             *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program allows your taskbot to follow a line in reverse.                                         *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The Light Sensor is attached to the back of the robot.                                          *|
|*    2)  Be sure to take readings of your Light Sensor over the light and dark areas.  Once you have     *|
|*        the values, add them and divide by 2 to find your threshold.  Then, use your threshold as a     *|
|*        comparison in your program.                                                                     *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port B                  motorB              NXT                 Right motor                         *|
|*    Port C                  motorC              NXT                 Left motor                          *|
|*    Port 1                  lightSensor         Light Sensor        Back mounted                        *|
/*---------------------------------------------------------------------------------------------------4246-*/


task main()
{
	TFileHandle   hFileHandle;								// will keep track of our files
	TFileIOResult nIOResult;									// will store our IO results
	string 				sFileName = "debug.txt";			// the name of our file
	int 					nFileSize = 10000;
	char 					sOutput[100];

	//Line Following Var.
	int Kp = 1000;
	int Ki = 0;
	int Kd = 0;
	int Tp = 50;
	int offset = 440;
	int integral = 0;
	int lastError = 0;
	int derivative = 0;
	int error = 0;
	int Turn = 0;

	int rawVal;
	int powerL, powerR;

	Delete(sFileName, nIOResult);
	OpenWrite(hFileHandle, nIOResult, sFileName, nFileSize);


	wait1Msec(50);           // The program waits 50 milliseconds to initialize the light sensor.

	while(1==1)
		wait1Msec(50);
	{
		rawVal = SensorRaw[lightSensor];
		error = lightSensor - offset;
		integral = integral + error;
		derivative = error - lastError;
		Turn = Kp*error + Ki*integral + Kd*derivative;
		Turn = Turn/100;
			motor[motorL] = Tp+Turn;
			motor[motorR] = Tp-Turn;
			lastError = error;
	/*	if(rawVal < 440)  // If the Light Sensor reads a value less than 45:
		{
			powerL = 80;
			powerR = 0;
		}
		else{
			powerL = 0;
			powerR = 80;
		}
			motor[motorB] = 0;
			motor[motorC] = 80;
			*/

			sprintf(sOutput, "val:%d powerL:%d powerR:%d /n", rawVal, powerL, powerR);
			WriteText(hFileHandle, nIOResult, sOutput);
	}
	Close(hFileHandle, nIOResult);
}
