#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
//#pragma config(Motor,  mtr_S1_C1_1,     ,              tmotorNone, openLoop)
//#pragma config(Motor,  mtr_S1_C1_2,     ,              tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to initialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	int powerL = 0;
	int powerR = 0;
	int y1Value = joystick.joy1_y1*(100/127);
	int x1Value;

	const float JOY_TO_MOTOR_SCALE = 100/127;
#define X_BUTT 1
#define B_BUTT 3
#define A_BUTT 2
#define Y_BUTT 4

	initializeRobot();

	//waitForStart();   // wait for start of tele-op phase

	while (1 == 1){
		wait10Msec(100);
		getJoystickSettings(joystick);
		nxtDisplayTextLine(1,"x1=%d",joystick.joy1_x1 );
		nxtDisplayTextLine(2,"y1=%d",joystick.joy1_y1 );
		nxtDisplayTextLine(3,"x2=%d",joystick.joy1_x2 );
		nxtDisplayTextLine(4,"y2=%d",joystick.joy1_y2 );
		nxtDisplayTextLine(5,"powerL=%d powerR=%d",powerL, powerR );

		y1Value = joystick.joy1_y1*JOY_TO_MOTOR_SCALE;
		x1Value = joystick.joy1_x1*JOY_TO_MOTOR_SCALE;


		if(joy1Btn(X_BUTT) == 1){
			motor[motorL] = powerL;
			motor[motorR] = powerR;
		}
		else if(joy1Btn(B_BUTT) == 1){
			motor[motorL] = 0;
			motor[motorR] = 0;

		}
		else if(joy1Btn(Y_BUTT) == 1){
			powerL = powerL+1;
			powerR = powerR+1;
			motor[motorL] = powerL;
			motor[motorR] = powerR;

		}
		else if(joy1Btn(A_BUTT) == 1){
			powerL = powerL-1;
			powerR = powerR-1;
			motor[motorL] = powerL;
			motor[motorR] = powerR;
		}

#if 0

		if(abs(joystick.joy1_x1)<3 && abs(joystick.joy1_y1)<3){						//Robot is still, no movement.
			motor[motorL] = 0;
			motor[motorR] = 0;
		}

		else if(abs(joystick.joy1_x1)<3 && (joystick.joy1_y1)>3){			// Robot is moving straight forward.
			motor[motorL] = joystick.joy1_y1;
			motor[motorR] = joystick.joy1_y1;
		}

		else if(abs(joystick.joy1_x1)<3 && (joystick.joy1_y1)<-3){				// Robot is moving straight backward.
			motor[motorL] = joystick.joy1_y1;
			motor[motorR] = joystick.joy1_y1;
		}

		else if( (joystick.joy1_x1)>3 && abs(joystick.joy1_y1)<3){			// Robot is rotating to the right.
			motor[motorL] = joystick.joy1_x1;
			motor[motorR] = -(joystick.joy1_x1);
		}

		else if( joystick.joy1_x1 < (-3) && abs(joystick.joy1_y1)<3){			// Robot is rotating to the left.
			motor[motorL] = joystick.joy1_x1;
			motor[motorR] = -(joystick.joy1_x1);
		}

		else if( (joystick.joy1_x1)>3 && (joystick.joy1_y1)>3){			// Robot is moving in a forward-right arc.

			powerR = joystick.joy1_y1 - (joystick.joy1_x1)/2;
			if(powerR<0){
				powerR = 0;
			}
			motor[motorR] = powerR;
			motor[motorL] = joystick.joy1_y1;
		}

		else if( (joystick.joy1_x1)>3 && (joystick.joy1_y1)< -3){			// Robot is moving in a backward-right arc.
			powerR = joystick.joy1_y1 + (joystick.joy1_x1)/2;

			if(powerR>0){
				powerR = 0;
			}
			motor[motorR] = powerR;
			motor[motorL] = joystick.joy1_y1;
		}

		else if( (joystick.joy1_x1)< -3 && (joystick.joy1_y1)< -3){			// Robot is moving in a backward-left arc.
			powerL = joystick.joy1_y1 - (joystick.joy1_x1)/2;
			if(powerL>0){
				powerL = 0;
			}
			motor[motorL] = powerL;

			motor[motorL] = joystick.joy1_y1;
		}

		else if( (joystick.joy1_x1)< -3 && (joystick.joy1_y1)>3){		// Robot is moving in a forward-left arc.
			powerL = joystick.joy1_y1 + (joystick.joy1_x1)/2;
			if(powerL<0){
				powerL = 0;
			}
			motor[motorL] = powerL;

			motor[motorR] = joystick.joy1_y1;
		}
#endif
	}

}








// Insert code to have servos and motors respond to joystick and button values.

// Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
// You may be able to find "snippets" of code that are similar to the functions that you want to
// perform.
