#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S2,     colorSensor,    sensorCOLORNONE)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	calibrateLightSensor();
while(SensorValue(colorSensor) <55)
{
	motor[motorC]  = 100;
	motor[motorB] = 100;
}

motor[motorC] = -75;
motor[motorB] = -75;

wait1Msec(1000);

}
